### ISSUE TITLE
Add command for revesing

### ISSUE THREAD

**Issue by LMech** [NayamAmarshe/ZorinGestures#1]
I really liked it, and i was actually was searching for some cool gestures, but i think you should add in the README a way to reverse the changes to make people try without fearing that they can't opt out.

Nice job btw :)

**Comment by NayamAmarshe** [comment]
> I really liked it, and i was actually was searching for some cool gestures, but i think you should add in the README a way to reverse the changes to make people try without fearing that they can't opt out.
> 
> Nice job btw :)

Thanks, I'll add instructions for undoing the changes  :)
